### ISSUE TITLE
PlatformIO Registry

### ISSUE THREAD

**Issue by Laxilef** [pstolarz/Arduino-Temperature-Control-Library#25]
Hi,
Your library has been a lifesaver after switching to kernel 3.1.x for ESP32, thanks for your work!

My suggestion: can you publish your libraries to PlatformIO Registry?
Now I use this method and it works well:
```ini
lib_deps = 
	...
	https://github.com/pstolarz/Arduino-Temperature-Control-Library.git#OneWireNg
```
But if you publish a new commit, I'm afraid something might suddenly break. Thanks!

**Comment by pstolarz** [comment]
@Laxilef thanks for using my lib. I'm glad it works for you.
If you are using DallasTemperature lib I'd recommend to switch to the original library not to my fork. To achive this you need to add Miles Burton's lib and my OneWireNg to `lib_deps` and disable Paul's OneWire by adding it to `lib_ignore`. Since OneWireNg is compatible via `OneWire.h` header with OneWire it will work. 
Alternatively you may use OneWireNg to talk with Dallas sensors and drop DallasTemperature lib utterly, since OneWireNg provides dedicated `DSTherm` driver exactly for this purpose. You may look at OneWireNg's `DallasTemperature` example for details.

**Comment by Laxilef** [comment]
Awesome! Thanks :)
